package app_utility;

public enum Constants {
    OPEN_DENT_FRAGMENT,
    SET_URI,
    IMAGE_SAVED,
    SHOW_FAB,
    HIDE_FAB,
    MENU_ITEM_SAVE,
    TRANSITION_FRAGMENT,
    MENU_ITEM_DELETE,
    DELETE_IMAGE,
    UPDATE_IMAGE_PATH,
    ADD_ALL_DATA,
    SAVE,
    UPDATE_TOTAL_TIME,
    UPDATE_TOTAL_COST,
    SUPER_BACK_PRESS,
    RESET_RECYCLER_VIEW,
    VIEWPAGER_POSITION_CHANGE
}
